In [1]:
import numpy as np

In [2]:
import sys
sys.path.insert(0, "/home/monica/Documents/2_ano/sistemas/si/") 
from src.si.feature_selection.select_percentile import SelectPercentile
from src.si.statistics.f_classification import f_classification

In [3]:
from src.si.io_folder.module_csv import read_csv

# Avaliação Aula 2 (03/10/2022)

## Exercício 3: Implementar o SelectPercentile

##### 3.1) Adiciona o objeto SelectPercentile ao sub-package feature_selection. Deves criar um módulo chamado select_percentile.py para implementar este objeto

##### 3.2) A class SelectPercentile tem uma arquitetura semelhante à classe SelectKBest. Considera a estrutura apresentada no diapositivo seguinte.

class SelectPercentile:

Parâmetros:
- score_func – função de análise da variância (f_classification ou f_regression)
- percentile – percentil para as features a selecionar

Parâmetros estimados:

- F – o valor de F para cada feature estimado pela score_func
- p – o valor de p para cada feature estimado pela score_func

Métodos:
- fit – estima o F e p para cada feature usando a scoring_func; retorna o self  (ele próprio)
- transform – seleciona as features com valor de F mais alto até ao percentil indicado. Por exemplo, para um dataset com 10 features e um percentil de 50%, o teu transform deve selecionar as 5 features com valor de F mais alto
- fit_transform – corre o fit e depois o transform

##### 3.3) Podes testar a class SelectPercentile num jupyter notebook usando o dataset iris.csv (classificação).

In [4]:
iris = read_csv('/home/monica/Documents/2_ano/sistemas/si/datasets/iris.csv', sep=',',features=True, label=True)
iris.X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
selector = SelectPercentile(score_func=f_classification, percentile=50)

selector.fit_transform(iris)

print(selector.p)
print(selector.F)

[1.66966919e-31 1.32791652e-16 3.05197580e-91 4.37695696e-85]
[ 119.26450218   47.3644614  1179.0343277   959.32440573]
