In [1]:
import numpy as np

In [2]:
import sys
sys.path.insert(0, "/home/monica/Documents/2_ano/sistemas/si/")
from src.si.data.dataset import Dataset
from src.si.neuronetworks.nn import NN
from src.si.neuronetworks.layer import Dense
from src.si.neuronetworks.sigmoid_activation import SigmoidActivation
from src.si.neuronetworks.soft_max_activation import SoftMaxActivation
from src.si.neuronetworks.re_lu_activation import ReLUActivation
from src.si.linear_model.ridge_regression import RidgeRegression
from src.si.linear_model.logistic_regression import LogisticRegression
from src.si.metrics.cross_entropy import cross_entropy, cross_entropy_derivative
from src.si.metrics.accuracy import accuracy
from src.si.metrics.mse import mse
from src.si.model_selection.split import train_test_split
import matplotlib.pyplot as plt
from src.si.io_folder.module_csv import read_csv
from sklearn import preprocessing


# Avaliação Aula 12 (12/12/2022)

## Exercício 12: Redes neuronais e Backpropagation

##### 12.1) Implementa o método de backward propagation da ReLUActivation layer.

Considera o seguinte para a propagação do erro numa layer de ativação ReLU:
- Substituir valores de erro superiores a 0 por 1
- Substituir valores de erro inferiores a 0 por 0
- Multiplicação elemento a elemento entre o erro e os valores anteriores

In [3]:
# adicionado no ficheiro src/si/neuronetworks/re_lu_activation.py

##### 12.2) Constrói um modelo de redes neuronais adequado ao dataset breast-bin.csv.

In [4]:
breast_bin = read_csv('/home/monica/Documents/2_ano/sistemas/si/datasets/breast-bin.csv', sep=',',features=True, label=True)

In [5]:
breast_bin.y[:20]
# binary problem

array([0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0.])

In [6]:
breast_bin.X = preprocessing.StandardScaler().fit_transform(breast_bin.X)
breast_bin_train, breast_bin_test = train_test_split(breast_bin, test_size=0.3)


In [7]:
print(breast_bin_train.shape())
print(breast_bin_test.shape())

(489, 9)
(209, 9)


In [8]:
# 3 layers with sigmoid activation

l1_bin = Dense(input_size = 9, output_size=9)
l2_bin = Dense(input_size = 9, output_size=9)
l3_bin = Dense(input_size = 9, output_size=1)

l1_bin_sa = ReLUActivation()
l2_bin_sa = ReLUActivation()
l3_bin_sa = SigmoidActivation()

model_bin = NN(layers=[ l1_bin, l1_bin_sa, l2_bin, l2_bin_sa, l3_bin, l3_bin_sa], loss_function=cross_entropy, loss_derivative=cross_entropy_derivative, verbose=True)

In [9]:
model_bin.fit(dataset=breast_bin_train)

 Epoch 0/1000 with cost: 0.228
 Epoch 1/1000 with cost: 0.264
 Epoch 2/1000 with cost: 0.291
 Epoch 3/1000 with cost: 0.311
 Epoch 4/1000 with cost: 0.325
 Epoch 5/1000 with cost: 0.335
 Epoch 6/1000 with cost: 0.343
 Epoch 7/1000 with cost: 0.349
 Epoch 8/1000 with cost: 0.353
 Epoch 9/1000 with cost: 0.356
 Epoch 10/1000 with cost: 0.358
 Epoch 11/1000 with cost: 0.36
 Epoch 12/1000 with cost: 0.361
 Epoch 13/1000 with cost: 0.363
 Epoch 14/1000 with cost: 0.363
 Epoch 15/1000 with cost: 0.364
 Epoch 16/1000 with cost: 0.364
 Epoch 17/1000 with cost: 0.365
 Epoch 18/1000 with cost: 0.365
 Epoch 19/1000 with cost: 0.365
 Epoch 20/1000 with cost: 0.365
 Epoch 21/1000 with cost: 0.365
 Epoch 22/1000 with cost: 0.365
 Epoch 23/1000 with cost: 0.366
 Epoch 24/1000 with cost: 0.366
 Epoch 25/1000 with cost: 0.366
 Epoch 26/1000 with cost: 0.366
 Epoch 27/1000 with cost: 0.366
 Epoch 28/1000 with cost: 0.366
 Epoch 29/1000 with cost: 0.366
 Epoch 30/1000 with cost: 0.366
 Epoch 31/1000 with

In [10]:
pred = model_bin.predict(breast_bin_test)
pred

array([[0.32959415],
       [0.33007494],
       [0.32923818],
       [0.32923747],
       [0.32923754],
       [0.32923396],
       [0.33005095],
       [0.32923755],
       [0.32923586],
       [0.3297242 ],
       [0.32923882],
       [0.32971934],
       [0.330012  ],
       [0.32955958],
       [0.3292357 ],
       [0.32923472],
       [0.32923754],
       [0.32923617],
       [0.3298279 ],
       [0.32923909],
       [0.32923974],
       [0.32995947],
       [0.32923572],
       [0.33054681],
       [0.33029055],
       [0.32936374],
       [0.32923472],
       [0.32923632],
       [0.32923627],
       [0.32923616],
       [0.33068909],
       [0.32923596],
       [0.33039155],
       [0.32923631],
       [0.32924001],
       [0.32923457],
       [0.32923947],
       [0.32923572],
       [0.32975908],
       [0.33090602],
       [0.32926038],
       [0.32923472],
       [0.3300297 ],
       [0.32924304],
       [0.32926486],
       [0.3296783 ],
       [0.33002728],
       [0.329

In [11]:
pred = np.where(pred>0.5, 1, 0).reshape(1,-1)
print(pred)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [12]:
score = accuracy(breast_bin_test.y,pred)
print(score)

0.6220095693779905


##### 12.3) Constrói um modelo de redes neuronais adequado ao dataset cpu.csv.

###### WORK IN PROGRESS 

In [13]:
cpu = read_csv('/home/monica/Documents/2_ano/sistemas/si/datasets/cpu.csv', sep=',',features=True, label=True)

In [14]:
cpu.y[:20]

# regression problem

array([ 198,  269,  220,  172,  132,  318,  367,  489,  636, 1144,   38,
         40,   92,  138,   10,   35,   19,   28,   31,  120])

In [15]:
cpu.X = preprocessing.StandardScaler().fit_transform(cpu.X)
cpu_train, cpu_test = train_test_split(cpu, test_size=0.3)

In [16]:
print(cpu_train.shape())
print(cpu_test.shape())

(147, 6)
(62, 6)


In [17]:
# 3 layers with ReLUActivation

# l1_reg = Dense(input_size = 6, output_size=6)
l2_reg = Dense(input_size = 6, output_size=4)
l3_reg = Dense(input_size = 4, output_size=1)

l1_reg_rlua = ReLUActivation()
l2_reg_rlua = ReLUActivation()

model_reg = NN(layers=[l1_reg_rlua, l2_reg, l2_reg_rlua, l3_reg], loss_function=cross_entropy, loss_derivative=cross_entropy_derivative, verbose=True)


In [18]:
model_reg.fit(dataset=cpu_train)

 Epoch 0/1000 with cost: nan
 Epoch 1/1000 with cost: -432.466
 Epoch 2/1000 with cost: -376.15
 Epoch 3/1000 with cost: -407.212
 Epoch 4/1000 with cost: -394.057
 Epoch 5/1000 with cost: -400.616
 Epoch 6/1000 with cost: -397.713
 Epoch 7/1000 with cost: -399.214
 Epoch 8/1000 with cost: -398.633
 Epoch 9/1000 with cost: -399.028
 Epoch 10/1000 with cost: -398.963
 Epoch 11/1000 with cost: -399.114
 Epoch 12/1000 with cost: -399.163
 Epoch 13/1000 with cost: -399.259
 Epoch 14/1000 with cost: -399.332
 Epoch 15/1000 with cost: -399.415
 Epoch 16/1000 with cost: -399.493
 Epoch 17/1000 with cost: -399.573
 Epoch 18/1000 with cost: -399.651
 Epoch 19/1000 with cost: -399.73
 Epoch 20/1000 with cost: -399.807
 Epoch 21/1000 with cost: -399.885
 Epoch 22/1000 with cost: -399.962
 Epoch 23/1000 with cost: -400.038
 Epoch 24/1000 with cost: -400.115
 Epoch 25/1000 with cost: -400.19
 Epoch 26/1000 with cost: -400.266
 Epoch 27/1000 with cost: -400.341
 Epoch 28/1000 with cost: -400.416
 Ep

/home/monica/Documents/2_ano/sistemas/si/src/si/metrics/cross_entropy.py:5: RuntimeWarning: divide by zero encountered in log
  return -np.sum(y_true*np.log(y_pred))/len(y_true)
/home/monica/Documents/2_ano/sistemas/si/src/si/metrics/cross_entropy.py:5: RuntimeWarning: invalid value encountered in log
  return -np.sum(y_true*np.log(y_pred))/len(y_true)


In [19]:
pred = model_reg.predict(dataset=cpu_test)

In [20]:
score = mse(cpu_test.y,pred)
print(score)

2094061.8329778227
