In [1]:
import numpy as np

In [2]:
import sys
sys.path.insert(0, "/home/monica/Documents/2_ano/sistemas/si/") 
from src.si.data.dataset import Dataset

In [3]:
from src.si.io_folder.module_csv import read_csv

# Avaliação Aula 1 (26-09-2022)

## Exercício 1: NumPy array Indexing/Slicing

##### 1.1 Neste exercício, vamos usar o iris dataset. Carrega o iris.csv usando o método read apropriado para o tipo de ficheiro.

In [4]:
iris = read_csv('/home/monica/Documents/2_ano/sistemas/si/datasets/iris.csv', sep=',',features=True, label=True)
iris.summary()

Média  Variância  Mediana  Mínimo  Máximo
0  5.843333   0.681122     5.80     4.3     7.9
1  3.054000   0.186751     3.00     2.0     4.4
2  3.758667   3.092425     4.35     1.0     6.9
3  1.198667   0.578532     1.30     0.1     2.5

##### 1.2) Seleciona a primeira variável independente e verifica a dimensão do array resultante.

In [5]:
var1 = iris.X[0]
print(iris.get_classes()[0])
print(var1)
print(var1.shape)

Iris-setosa
[5.1 3.5 1.4 0.2]
(4,)


##### 1.3) Seleciona as últimas 5 amostras do iris dataset. Qual a média das últimas 5 amostras para cada variável independente/feature?

In [6]:
ultimas_amostras = iris.X[-5:]
print(ultimas_amostras, '\n')
print('Média para cada variável das 5 amostras: ', ultimas_amostras.mean(axis=0))

[[6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]] 

Média para cada variável das 5 amostras:  [6.32 2.98 5.18 2.06]


##### 1.4) Seleciona todas as amostras do dataset com valor superior ou igual a 1. Nota que o array resultante deve ter apenas amostras com valores iguais ou superiores a 1 para todas as features.

In [7]:
a = iris.X[(iris.X[:,0] >= 1) & (iris.X[:,1] >= 1) & (iris.X[:,2] >= 1) & (iris.X[:,3] >= 1)]
print(a.shape)
# print(a)

(100, 4)


##### 1.5) Seleciona todas as amostras com a classe/label igual a ‘Iris- setosa’. Quantas amostras obténs?

In [8]:
b = iris.X[iris.y == 'Iris-setosa']
print(b.shape)

(50, 4)


## Exercicio 2

##### 2.1) Adiciona um método ao objeto Dataset que remove todas as amostras que contêm pelo menos um valor nulo (NaN). Nota que o objeto resultante não deve conter valores nulos em para nenhuma feature/variável independente. Nota também que deves atualizar o vetor y removendo as entradas associadas às amostras a remover. Deves usar apenas funções no NumPy. Nome do método: dropna

In [9]:
# Alterado diretamente no objeto Dataset.

In [12]:
# Exemplo
x = np.array([[1, 2, 3], [3, 1, 3]])
y = np.array([5, 5])
features = ['A', 'B', 'C']
dataset = Dataset(x, y, features, 'as')
x2 = np.array([[1, 2, 3], [3, 1, np.nan]])
dataset2 = Dataset(x2, y, features, 'label')
print('Dataset 2:\n', dataset2.X)
dataset2.dropna()
print('Dataset 2 depois de dropna()):\n', dataset2.X)

Dataset 2:
 [[ 1.  2.  3.]
 [ 3.  1. nan]]
Dataset 2 depois de dropna()):
 [[1. 2. 3.]]


##### 2.2) Adiciona um método ao objeto Dataset que substitui todas os valores nulos por outro valor (argumento da função/método). Nota que o objeto resultante não deve conter valores nulos em para nenhuma feature/variável independente. Deves usar apenas funções no NumPy. Nome do método: fillna

In [11]:
# Alterado diretamente no objeto Dataset.

In [13]:
# Exemplo:

dataset2 = Dataset(x2, y, features, 'label')
dataset2.fillna(100)
print('Dataset 2 depois de fillna(100):\n', dataset2.X)

Dataset 2 depois de fillna(100):
 [[  1.   2.   3.]
 [  3.   1. 100.]]
